name: project_pilot
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  rxdart: ^0.27.2
  flutter_html: ^2.1.2

  cupertino_icons: ^1.0.2
  http: 0.13.3
  flutter_search_bar: ^2.1.0
  flutter_native_splash: ^1.2.3

flutter_native_splash:
  image: assets/images/splash_screen.png
  android: true
  color: "#ffffff"
  android_gravity: fill



dev_dependencies:
  flutter_test:
    sdk: flutter


# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: robotoMedium
      fonts:
        - asset: assets/font/Roboto-Medium.ttf
    - family: robotoRegular
      fonts:
        - asset: assets/font/Roboto-Regular.ttf